package com.aikshika.entity;
// Generated Nov 23, 2016 7:07:07 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Mststudenttimetable generated by hbm2java
 */
@Entity
@Table(name = "mststudenttimetable", catalog = "dbschoolmanagementsystem")
public class Mststudenttimetable implements java.io.Serializable {

	private Integer intStudentTimeTableId;
	private Mststudclass mststudclass;
	private Mststudclasssection mststudclasssection;
	private Mstsubject mstsubject;
	private Msttimings msttimings;
	private Tbldaysofweek tbldaysofweek;
	private Integer intStatus;
	private Integer intStudentStatus;

	public Mststudenttimetable() {
	}

	public Mststudenttimetable(Mststudclass mststudclass, Mststudclasssection mststudclasssection,
			Mstsubject mstsubject, Msttimings msttimings, Tbldaysofweek tbldaysofweek, Integer intStatus, Integer intStudentStatus) {
		this.mststudclass = mststudclass;
		this.mststudclasssection = mststudclasssection;
		this.mstsubject = mstsubject;
		this.msttimings = msttimings;
		this.tbldaysofweek = tbldaysofweek;
		this.intStatus = intStatus;
		this.intStudentStatus = intStudentStatus;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "intStudentTimeTableID", unique = true, nullable = false)
	public Integer getIntStudentTimeTableId() {
		return this.intStudentTimeTableId;
	}

	public void setIntStudentTimeTableId(Integer intStudentTimeTableId) {
		this.intStudentTimeTableId = intStudentTimeTableId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intClassId")
	public Mststudclass getMststudclass() {
		return this.mststudclass;
	}

	public void setMststudclass(Mststudclass mststudclass) {
		this.mststudclass = mststudclass;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intSectionId")
	public Mststudclasssection getMststudclasssection() {
		return this.mststudclasssection;
	}

	public void setMststudclasssection(Mststudclasssection mststudclasssection) {
		this.mststudclasssection = mststudclasssection;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intSubjectId")
	public Mstsubject getMstsubject() {
		return this.mstsubject;
	}

	public void setMstsubject(Mstsubject mstsubject) {
		this.mstsubject = mstsubject;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intMsttimingsId")
	public Msttimings getMsttimings() {
		return this.msttimings;
	}

	public void setMsttimings(Msttimings msttimings) {
		this.msttimings = msttimings;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intDaysID")
	public Tbldaysofweek getTbldaysofweek() {
		return this.tbldaysofweek;
	}

	public void setTbldaysofweek(Tbldaysofweek tbldaysofweek) {
		this.tbldaysofweek = tbldaysofweek;
	}

	@Column(name = "intStatus")
	public Integer getIntStatus() {
		return this.intStatus;
	}

	public void setIntStatus(Integer intStatus) {
		this.intStatus = intStatus;
	}

	@Column(name = "intStudentStatus")
	public Integer getIntStudentStatus() {
		return intStudentStatus;
	}

	public void setIntStudentStatus(Integer intStudentStatus) {
		this.intStudentStatus = intStudentStatus;
	}

}
