package com.aikshika.entity;
// Generated Nov 23, 2016 7:07:07 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mstteachertimetable generated by hbm2java
 */
@Entity
@Table(name = "mstteachertimetable", catalog = "dbschoolmanagementsystem")
public class Mstteachertimetable implements java.io.Serializable {

	private Integer intTeacherTimeTableId;
	private Mstregistration mstregistration;
	private Mststudclass mststudclass;
	private Mststudclasssection mststudclasssection;
	private Mstsubject mstsubject;
	private Msttimings msttimings;
	private Tbldaysofweek tbldaysofweek;
	private Integer intStatus;
	private Date dtAssignDate;
	private Integer intTeacherStatus;
	
	private Set<Mstteachercheckin> mstteachercheckins = new HashSet<Mstteachercheckin>(0);

	public Mstteachertimetable() {
	}

	public Mstteachertimetable(Mstregistration mstregistration, Mststudclass mststudclass,
			Mststudclasssection mststudclasssection, Mstsubject mstsubject, Msttimings msttimings,
			Tbldaysofweek tbldaysofweek, Integer intStatus,Date dtAssignDate, Integer intTeacherStatus,Set<Mstteachercheckin> mstteachercheckins) {
		this.mstregistration = mstregistration;
		this.mststudclass = mststudclass;
		this.mststudclasssection = mststudclasssection;
		this.mstsubject = mstsubject;
		this.msttimings = msttimings;
		this.tbldaysofweek = tbldaysofweek;
		this.intStatus = intStatus;
		this.dtAssignDate = dtAssignDate;
		this.intTeacherStatus = intTeacherStatus;
		this.mstteachercheckins = mstteachercheckins;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "intTeacherTimeTableId", unique = true, nullable = false)
	public Integer getIntTeacherTimeTableId() {
		return this.intTeacherTimeTableId;
	}

	public void setIntTeacherTimeTableId(Integer intTeacherTimeTableId) {
		this.intTeacherTimeTableId = intTeacherTimeTableId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intRegistrationId")
	public Mstregistration getMstregistration() {
		return this.mstregistration;
	}

	public void setMstregistration(Mstregistration mstregistration) {
		this.mstregistration = mstregistration;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intClassId")
	public Mststudclass getMststudclass() {
		return this.mststudclass;
	}

	public void setMststudclass(Mststudclass mststudclass) {
		this.mststudclass = mststudclass;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intSectionId")
	public Mststudclasssection getMststudclasssection() {
		return this.mststudclasssection;
	}

	public void setMststudclasssection(Mststudclasssection mststudclasssection) {
		this.mststudclasssection = mststudclasssection;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intSubjectId")
	public Mstsubject getMstsubject() {
		return this.mstsubject;
	}

	public void setMstsubject(Mstsubject mstsubject) {
		this.mstsubject = mstsubject;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intMsttimingsId")
	public Msttimings getMsttimings() {
		return this.msttimings;
	}

	public void setMsttimings(Msttimings msttimings) {
		this.msttimings = msttimings;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "intDaysID")
	public Tbldaysofweek getTbldaysofweek() {
		return this.tbldaysofweek;
	}

	public void setTbldaysofweek(Tbldaysofweek tbldaysofweek) {
		this.tbldaysofweek = tbldaysofweek;
	}

	@Column(name = "intStatus")
	public Integer getIntStatus() {
		return this.intStatus;
	}

	public void setIntStatus(Integer intStatus) {
		this.intStatus = intStatus;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "mstteachertimetable")
	public Set<Mstteachercheckin> getMstteachercheckins() {
		return this.mstteachercheckins;
	}

	public void setMstteachercheckins(Set<Mstteachercheckin> mstteachercheckins) {
		this.mstteachercheckins = mstteachercheckins;
	}

	@Column(name = "dtAssignDate")
	@Temporal(TemporalType.DATE)
	public Date getDtAssignDate() {
		return dtAssignDate;
	}

	public void setDtAssignDate(Date dtAssignDate) {
		this.dtAssignDate = dtAssignDate;
	}

	@Column(name = "intTeacherStatus")
	public Integer getIntTeacherStatus() {
		return intTeacherStatus;
	}

	public void setIntTeacherStatus(Integer intTeacherStatus) {
		this.intTeacherStatus = intTeacherStatus;
	}

	
}
